version: "3"
services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: app-mailhog
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # HTTP Server
    restart: unless-stopped
