version: "3"
services:
  scylla-node1:
    image: scylladb/scylla:4.4.5
    container_name: app-scylla-node1
    command: --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042"
      - "9142:9142"
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "10000:10000"
    restart: unless-stopped

  scylla-manager:
    image: scylladb/scylla-manager:2.5.1
    container_name: app-scylla-manager
    depends_on:
      - scylla-node1
    restart: unless-stopped
